# Generated by Django 2.2.14 on 2020-07-01 18:18

from django.db import migrations, models
import django_kms.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_string', django_kms.fields.KMSEncryptedStringField(editable=True, key_id='alias/fake-key')),
            ],
        ),
    ]
